---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 4.1.3
  values:
    admin:
      existingSecret: grafana-admin-credentials

    service:
      type: NodePort
      port: 3000
      nodePort: 32003

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.loki:3100
            jsonData:
              maxLines: 2000
